# Introduction to Tensorflow 2.0

* A Tensor is a multi-dimensional array that has the ability to run on the GPU
* A tensor is an N dimensional array of data



Start with Basic operations

* Requires the latest pip - pip install --upgrade pip

* Current stable release for CPU and GPU - pip install tensorflow


In [103]:
! pip install --upgrade pip -q
! pip install tensorflow -q

## Tensor Basic

In [104]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2' # avoid warnings
import tensorflow as tf

In [105]:
# Initialization of a Tensor
x=tf.constant(4)
print(x)
x=tf.constant(4.0)
print(x)
x=tf.constant(4,shape=(1,1))
print(x)
x=tf.constant(4,shape=(1,1),dtype=tf.float32)
print(x)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor([[4]], shape=(1, 1), dtype=int32)
tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [106]:
x=tf.constant([[1,2,3],[4,5,6]])
print(x)
x=tf.zeros((2,3))
print(x)
x=tf.ones((2,3))
print(x)
x=tf.eye((3))
print(x)
x=tf.random.normal((2,3),mean=0,stddev=1)
print(x)
x=tf.range(start=1,limit=10,delta=1,dtype=tf.float32)
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.8344148  -0.05043352  0.2141907 ]
 [ 0.01153478  0.6537778  -0.7286184 ]], shape=(2, 3), dtype=float32)
tf.Tensor([1. 2. 3. 4. 5. 6. 7. 8. 9.], shape=(9,), dtype=float32)


In [107]:
# convert dtype
x=tf.cast(x,dtype=tf.int64)
print(x)


tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int64)


In [108]:
# math operations
x=tf.constant([[1,2,3],[4,5,6]],dtype=tf.int32)
y=tf.constant([[1,2,3],[4,5,6]])
z=tf.add(x,y)
print(z)
print(x+y)

x=tf.constant([[1,2,3],[4,5,6]],dtype=tf.float32)
y=tf.constant([[1,2,3],[4,5,6]],dtype=tf.float32)
z=tf.add(x,y)
print(z)

print(x*y)
print(tf.multiply(x,y))

print(x/y)
print(tf.divide(x,y))

tf.Tensor(
[[ 2  4  6]
 [ 8 10 12]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 2  4  6]
 [ 8 10 12]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 2.  4.  6.]
 [ 8. 10. 12.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [109]:
print(tf.tensordot(x,y,axes=2))
print(tf.tensordot(x,y,axes=0))

tf.Tensor(91.0, shape=(), dtype=float32)
tf.Tensor(
[[[[ 1.  2.  3.]
   [ 4.  5.  6.]]

  [[ 2.  4.  6.]
   [ 8. 10. 12.]]

  [[ 3.  6.  9.]
   [12. 15. 18.]]]


 [[[ 4.  8. 12.]
   [16. 20. 24.]]

  [[ 5. 10. 15.]
   [20. 25. 30.]]

  [[ 6. 12. 18.]
   [24. 30. 36.]]]], shape=(2, 3, 2, 3), dtype=float32)


In [110]:
# Matrix operation
x=tf.random.normal((2,3))
y=tf.random.normal((3,4))
print(tf.matmul(x,y))


tf.Tensor(
[[ 4.7634425   1.4388988  -5.41208    -3.5165195 ]
 [ 0.7529469  -0.057588    0.11500758 -0.41020483]], shape=(2, 4), dtype=float32)


In [111]:
# Indexing 
x=tf.constant([1,2,3,4,5,6,7,8,9])
print(x)
print(x[4])
print(x[2:6])
print(x[4:-1])
print(x[::2])
print(x[::-1])

# pick values at certain indices from a tensor
indices=[0,3,7]
x_ind=tf.gather(x,indices)
print(x_ind)

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([3 4 5 6], shape=(4,), dtype=int32)
tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)
tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)
tf.Tensor([9 8 7 6 5 4 3 2 1], shape=(9,), dtype=int32)
tf.Tensor([1 4 8], shape=(3,), dtype=int32)


In [112]:
x=tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print(x[:,0])
print(x[:,1])
print(x[:,2])

print(x[0:2,1])


tf.Tensor([1 4 7], shape=(3,), dtype=int32)
tf.Tensor([2 5 8], shape=(3,), dtype=int32)
tf.Tensor([3 6 9], shape=(3,), dtype=int32)
tf.Tensor([2 5], shape=(2,), dtype=int32)


In [113]:
# Reshaping the tensor
x=tf.range(9)
print(tf.reshape(x,(3,3)))

x=tf.range(12)
print(tf.reshape(x,(4,3)))

x=tf.range(12)
print(tf.reshape(x,(3,4)))

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]], shape=(3, 4), dtype=int32)


In [114]:
# Transpose
x=tf.reshape(tf.range(9),(3,3))
print(x)
print(tf.transpose(x))

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)


## Neural Networks with Sequential and Functional API

Keras is official higher level api ans is essentially the go-to when bulding a neural network and models in tensorflow

In [122]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

In [123]:
(x_train,y_train),(x_test,y_test) = mnist.load_data()

In [124]:
print(x_train.shape,y_train.shape)
print(x_test.shape,y_test.shape)
print(x_train[0].shape)
print(type(x_train[0]))

(60000, 28, 28) (60000,)
(10000, 28, 28) (10000,)
(28, 28)
<class 'numpy.ndarray'>


In [125]:
x_train=x_train.reshape(-1,28*28).astype("float32")/255
print(x_train.shape),print(type(x_train))
x_test=x_test.reshape(-1,28*28).astype("float32")/255
print(x_test.shape),print(type(x_test))

(60000, 784)
<class 'numpy.ndarray'>
(10000, 784)
<class 'numpy.ndarray'>


(None, None)

Using Sequential APIs - its convenient but not flexible

In [134]:
model = keras.Sequential()
model.add(keras.Input(shape=(784,)))
model.add(layers.Dense(512, activation="relu"))
model.add(layers.Dense(256, activation="relu", name="my_layer"))
model.add(layers.Dense(10))

In [136]:
# Functional API (A bit more flexible)
inputs = keras.Input(shape=(784,))
x = layers.Dense(512, activation="relu", name="first_layer")(inputs)
x = layers.Dense(256, activation="relu", name="second_layer")(x)
outputs = layers.Dense(10, activation="softmax")(x)
model = keras.Model(inputs=inputs, outputs=outputs)

In [138]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    metrics=["accuracy"],
)

In [140]:
print(model.summary())

Model: "functional_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_12 (InputLayer)     │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ first_layer (Dense)             │ (None, 512)            │       401,920 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ second_layer (Dense)            │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 10)             │         2,570 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,607,456 (6.13 MB)

 Trainable params: 535,818 (2.04 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,071,638 (4.09 MB)

None


In [139]:
model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)
model.evaluate(x_test, y_test, batch_size=32, verbose=2)

Epoch 1/5
1875/1875 - 4s - 2ms/step - accuracy: 0.9439 - loss: 0.1837
Epoch 2/5
1875/1875 - 4s - 2ms/step - accuracy: 0.9756 - loss: 0.0783
Epoch 3/5
1875/1875 - 3s - 2ms/step - accuracy: 0.9828 - loss: 0.0540
Epoch 4/5
1875/1875 - 4s - 2ms/step - accuracy: 0.9872 - loss: 0.0398
Epoch 5/5
1875/1875 - 4s - 2ms/step - accuracy: 0.9895 - loss: 0.0335
313/313 - 0s - 825us/step - accuracy: 0.9811 - loss: 0.0730


[0.07303323596715927, 0.9811000227928162]