# Introduction to Tensorflow 2.0

* A Tensor is a multi-dimensional array that has the ability to run on the GPU
* A tensor is an N dimensional array of data



Start with Basic operations

* Requires the latest pip - pip install --upgrade pip

* Current stable release for CPU and GPU - pip install tensorflow


In [3]:
! pip install --upgrade pip -q
! pip install tensorflow -q

In [3]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2' # avoid warnings
import tensorflow as tf

In [8]:
# Initialization of a Tensor
x=tf.constant(4)
print(x)
x=tf.constant(4.0)
print(x)
x=tf.constant(4,shape=(1,1))
print(x)
x=tf.constant(4,shape=(1,1),dtype=tf.float32)
print(x)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor([[4]], shape=(1, 1), dtype=int32)
tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [18]:
x=tf.constant([[1,2,3],[4,5,6]])
print(x)
x=tf.zeros((2,3))
print(x)
x=tf.ones((2,3))
print(x)
x=tf.eye((3))
print(x)
x=tf.random.normal((2,3),mean=0,stddev=1)
print(x)
x=tf.range(start=1,limit=10,delta=1,dtype=tf.float32)
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.03469208  2.3787212  -0.82017267]
 [ 0.6709153  -0.572818   -0.04566335]], shape=(2, 3), dtype=float32)
tf.Tensor([1. 2. 3. 4. 5. 6. 7. 8. 9.], shape=(9,), dtype=float32)


In [21]:
# convert dtype
x=tf.cast(x,dtype=tf.int64)
print(x)


tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int64)


In [39]:
# math operations
x=tf.constant([[1,2,3],[4,5,6]],dtype=tf.int32)
y=tf.constant([[1,2,3],[4,5,6]])
z=tf.add(x,y)
print(z)
print(x+y)

x=tf.constant([[1,2,3],[4,5,6]],dtype=tf.float32)
y=tf.constant([[1,2,3],[4,5,6]],dtype=tf.float32)
z=tf.add(x,y)
print(z)

print(x*y)
print(tf.multiply(x,y))

print(x/y)
print(tf.divide(x,y))

tf.Tensor(
[[ 2  4  6]
 [ 8 10 12]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 2  4  6]
 [ 8 10 12]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 2.  4.  6.]
 [ 8. 10. 12.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [38]:
print(tf.tensordot(x,y,axes=2))
print(tf.tensordot(x,y,axes=0))

tf.Tensor(91.0, shape=(), dtype=float32)
tf.Tensor(
[[[[ 1.  2.  3.]
   [ 4.  5.  6.]]

  [[ 2.  4.  6.]
   [ 8. 10. 12.]]

  [[ 3.  6.  9.]
   [12. 15. 18.]]]


 [[[ 4.  8. 12.]
   [16. 20. 24.]]

  [[ 5. 10. 15.]
   [20. 25. 30.]]

  [[ 6. 12. 18.]
   [24. 30. 36.]]]], shape=(2, 3, 2, 3), dtype=float32)


In [43]:
# Matrix operation
x=tf.random.normal((2,3))
y=tf.random.normal((3,4))
print(tf.matmul(x,y))


tf.Tensor(
[[-0.06888774  0.40660852 -0.9388473  -1.0908937 ]
 [-1.237572    1.0453576  -2.5798485  -0.8332591 ]], shape=(2, 4), dtype=float32)


In [50]:
# Indexing 
x=tf.constant([1,2,3,4,5,6,7,8,9])
print(x)
print(x[4])
print(x[2:6])
print(x[4:-1])
print(x[::2])
print(x[::-1])

# pick values at certain indices from a tensor
indices=[0,3,7]
x_ind=tf.gather(x,indices)
print(x_ind)

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([3 4 5 6], shape=(4,), dtype=int32)
tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)
tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)
tf.Tensor([9 8 7 6 5 4 3 2 1], shape=(9,), dtype=int32)
tf.Tensor([1 4 8], shape=(3,), dtype=int32)
